config/routes.rb
WdiBackgroundJobs::Application.routes.draw do
  resources :fans

  root 'fans#new'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/fan.rb
class Fan < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fans_controller.rb
class FansController < ApplicationController
  before_action :set_fan, only: [:show, :edit, :update, :destroy]

  # GET /fans
  # GET /fans.json
  def index
    @fans = Fan.all
    Sleeper.perform_async(10)
  end

  # GET /fans/1
  # GET /fans/1.json
  def show
  end

  # GET /fans/new
  def new
    @fan = Fan.new
  end

  # GET /fans/1/edit
  def edit
  end

  # POST /fans
  # POST /fans.json
  def create
    @fan = Fan.new(fan_params)

    respond_to do |format|
      if @fan.save
        FanMailer.delay.welcome(@fan.id)
        format.html { redirect_to @fan, notice: 'Fan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fan }
      else
        format.html { render action: 'new' }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fans/1
  # PATCH/PUT /fans/1.json
  def update
    respond_to do |format|
      if @fan.update(fan_params)
        format.html { redirect_to @fan, notice: 'Fan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fans/1
  # DELETE /fans/1.json
  def destroy
    @fan.destroy
    respond_to do |format|
      format.html { redirect_to fans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan
      @fan = Fan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fan_params
      params.require(:fan).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fans_helper.rb
module FansHelper
end

app/views/fans/_form.html.erb
<%= form_for(@fan) do |f| %>
  <% if @fan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fan.errors.count, "error") %> prohibited this fan from being saved:</h2>

      <ul>
      <% @fan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/fans/edit.html.erb
<h1>Editing fan</h1>

<%= render 'form' %>

<%= link_to 'Show', @fan %> |
<%= link_to 'Back', fans_path %>

app/views/fans/index.html.erb
<h1>Listing fans</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fans.each do |fan| %>
      <tr>
        <td><%= fan.email %></td>
        <td><%= link_to 'Show', fan %></td>
        <td><%= link_to 'Edit', edit_fan_path(fan) %></td>
        <td><%= link_to 'Destroy', fan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fan', new_fan_path %>

app/views/fans/new.html.erb
<!-- <h1>New fan</h1> -->

<%#= render 'form' %>

<%#= link_to 'Back', fans_path %>

<div class="container">
  <style type="text/css">
  .landing {
  	color: #FFF;
  	background: rgba(0, 0, 0, .7);
  	width: 600px;
      margin: 0 auto;
    padding: 80px;
    -webkit-border-radius: 6px;
		-moz-border-radius: 6px;
		border-radius: 6px;
  }
  .bg-stretch {
  	background-image: url("/assets/background.jpg") !important;
  	background-repeat: no-repeat !important;
  	background: url(/assets/background.jpg) no-repeat center center fixed;
  	-webkit-background-size: cover;
  	-moz-background-size: cover;
  	-o-background-size: cover;
  	background-size: cover;
  	width: 100%;
  	height: 100%;
  	margin: 0;
  	padding: 0;
  	position: absolute;
  	top: 0;
  	left: 0;
      z-index: -1;
  }
  </style>
  <div id="user_nav">
  </div>
  <div class="bg-stretch"></div>
  <br>
  <br>
  <br>
  <div class="hero-unit landing">
    <center>
      <h1>THE MILES YOU RUN</h1>
      <h2>solve a problem for a person in need</h2>
             
          <p>Join us and help a real person</p>

					<%= form_for(@fan) do |f| %>
					  <% if @fan.errors.any? %>
					    <div id="error_explanation">
					      <h2><%= pluralize(@fan.errors.count, "error") %> prohibited this fan from being saved:</h2>

					      <ul>
					      <% @fan.errors.full_messages.each do |msg| %>
					        <li><%= msg %></li>
					      <% end %>
					      </ul>
					    </div>
					  <% end %>

					  <div class="field" style="margin-top: 50px">
					    <%= f.text_field :email, placeholder: "Email Address", style: "color: #000" %>
					  </div>
					  <div class="actions" style="margin-top: 20px">
					    <%= f.submit "Count me in!", class: "btn btn-primary btn-large" %>
					  </div>
					<% end %>

    </center>
  </div>
</div>

app/views/fans/show.html.erb
<h1>Thanks for signing up <%= @fan.email %>!</h1>
<h2>Our email robots are sending you a welcome message with instructions on how to make a difference.</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WdiBackgroundJobs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>